const { Router, CustomCacheKey } = require('@xdn/core/router')
const { nextRoutes, renderNextPage } = require('@xdn/next')
const key = new CustomCacheKey().excludeAllQueryParametersExcept('query', 'version')

const htmlCacheConfig = {
  key,
  browser: {
    maxAgeSeconds: 0,
    serviceWorkerSeconds: 0,
  },
  edge: {
    maxAgeSeconds: 60 * 60 * 24 * 365,
    staleWhileRevalidateSeconds: 60 * 60 * 24 * 365,
  },
}

const apiCacheConfig = {
  key,
  browser: {
    maxAgeSeconds: 0,
    serviceWorkerSeconds: 60 * 60,
  },
  edge: {
    maxAgeSeconds: 60 * 60 * 24 * 365,
    staleWhileRevalidateSeconds: 60 * 60 * 24 * 365,
  },
}

const staticCacheConfig = {
  key,
  browser: {
    maxAgeSeconds: 60 * 60,
    serviceWorkerSeconds: 60 * 60,
  },
  edge: {
    maxAgeSeconds: 60 * 60 * 24 * 365,
    staleWhileRevalidateSeconds: 60 * 60 * 24 * 365,
  },
}

const testRouteHandler = ({ proxy }) => {
  proxy('api')
}

const router = new Router().match('/service-worker.js', ({ cache, serveStatic }) => {
  cache({
    browser: {
      maxAgeSeconds: 0,
    },
    edge: {
      maxAgeSeconds: 60 * 60 * 365,
    },
  })
  serveStatic('.next/static/service-worker.js')
})
router
  .get('/images/:path*', ({ cache }) => {
    cache(staticCacheConfig)
  })
  // the following route is needed for older guides and should not be removed
  .match('/guides/images/:path*', ({ cache, serveStatic }) => {
    cache(staticCacheConfig)
    serveStatic('public/images/:path*')
  })
  .match('/api/:path*', ({ cache }) => {
    cache(apiCacheConfig)
  })
  .match('/docs/api/:path*/', ({ proxy, cache }) => {
    cache(htmlCacheConfig)
    proxy('api', { path: '/xdn-docs-pages/current/api/:path*/' })
  })
  .match('/docs/api/:path*', ({ proxy, cache }) => {
    cache(htmlCacheConfig)
    proxy('api', { path: '/xdn-docs-pages/current/api/:path*' })
  })
  .match('/docs/:version/api/:path*/', ({ proxy, cache }) => {
    cache(htmlCacheConfig)
    proxy('api', { path: '/xdn-docs-pages/:version/api/:path*/' })
  })
  .match('/docs/:version/api/:path*', ({ proxy, cache }) => {
    cache(htmlCacheConfig)
    proxy('api', { path: '/xdn-docs-pages/:version/api/:path*' })
  })
router.get('/used-:path*', testRouteHandler)
router.get('/lcd-:path*', testRouteHandler)
router.get('/miscellaneous-:path*', testRouteHandler)
router.get('/cheap-:path*', testRouteHandler)
router.get('/parts-:path*', testRouteHandler)
router.get('/laptop-:path*', testRouteHandler)
router.get('/laptops-:path*', testRouteHandler)
router.get('/laptops/:path*', testRouteHandler)
router.get('/computer-:path*', testRouteHandler)
router.get('/computers-:path*', testRouteHandler)
router.get('/computers/:path*', testRouteHandler)
router.get('/accessories/:path*', testRouteHandler)
router.get('/cables/:path*', testRouteHandler)
router.get('/auxiliary-:path*', testRouteHandler)
router.get('/refurbished-:path*', testRouteHandler)
router.get('/core-:path*', testRouteHandler)
router.get('/xeon-:path*', testRouteHandler)
router.get('/new-:path*', testRouteHandler)
router.get('/pcs-:path*', testRouteHandler)
router.get('/memory/:path*', testRouteHandler)
router.get('/pawn-:path*', testRouteHandler)
/**
 * Pages: brands // PLP(s) & PDP(s)
 */
router.get('/brands/:path*', testRouteHandler)
router.get('/brands-:path*', testRouteHandler)
router.get('/xpg-:path*', testRouteHandler)
router.get('/yi-:path*', testRouteHandler)
router.get('/yoko-:path*', testRouteHandler)
router.get('/youmaker-:path*', testRouteHandler)
router.get('/z-machine-:path*', testRouteHandler)
router.get('/zalman-:path*', testRouteHandler)
router.get('/zealot-:path*', testRouteHandler)
router.get('/zebra-:path*', testRouteHandler)
router.get('/zeiss-:path*', testRouteHandler)
router.get('/zivigo-:path*', testRouteHandler)
router.get('/zkteco-:path*', testRouteHandler)
router.get('/zotac-:path*', testRouteHandler)
router.get('/ultra-x3-:path*', testRouteHandler)
router.get('/unirex-:path*', testRouteHandler)
router.get('/unit-:path*', testRouteHandler)
router.get('/universal-remote-:path*', testRouteHandler)
router.get('/urban-armor-gear-:path*', testRouteHandler)
router.get('/valve-:path*', testRouteHandler)
router.get('/vantec-usa-:path*', testRouteHandler)
router.get('/varizoom-:path*', testRouteHandler)
router.get('/vault-:path*', testRouteHandler)
router.get('/velbon-:path*', testRouteHandler)
router.get('/vello-:path*', testRouteHandler)
router.get('/velodyne-:path*', testRouteHandler)
router.get('/verbatim-:path*', testRouteHandler)
router.get('/villain-:path*', testRouteHandler)
router.get('/visiontek-:path*', testRouteHandler)
router.get('/vivid-:path*', testRouteHandler)
router.get('/volex-:path*', testRouteHandler)
router.get('/vrizoom-:path*', testRouteHandler)
router.get('/vupoint-:path*', testRouteHandler)
router.get('/w-box-:path*', testRouteHandler)
router.get('/watchguard-:path*', testRouteHandler)
router.get('/wd-:path*', testRouteHandler)
router.get('/wemo-:path*', testRouteHandler)
router.get('/whistle-:path*', testRouteHandler)
router.get('/whynter-:path*', testRouteHandler)
router.get('/wifi-texas-:path*', testRouteHandler)
router.get('/wink-:path*', testRouteHandler)
router.get('/world-charge-:path*', testRouteHandler)
router.get('/x-fan-:path*', testRouteHandler)
router.get('/xbox-:path*', testRouteHandler)
router.get('/xcy-:path*', testRouteHandler)
router.get('/xiaomi-mijia-:path*', testRouteHandler)
router.get('/xigmatek-:path*', testRouteHandler)
router.get('/soundblaster-:path*', testRouteHandler)
router.get('/soundtube-:path*', testRouteHandler)
router.get('/ssa-:path*', testRouteHandler)
router.get('/stec-:path*', testRouteHandler)
router.get('/streamsmart-:path*', testRouteHandler)
router.get('/sunpak-:path*', testRouteHandler)
router.get('/supermicro-:path*', testRouteHandler)
router.get('/surface-pro-3-:path*', testRouteHandler)
router.get('/surface-pro-4-:path*', testRouteHandler)
router.get('/syba-:path*', testRouteHandler)
router.get('/symbol-:path*', testRouteHandler)
router.get('/t-mobile-:path*', testRouteHandler)
router.get('/tamrac-:path*', testRouteHandler)
router.get('/taskmates-:path*', testRouteHandler)
router.get('/team-group-:path*', testRouteHandler)
router.get('/teemi-:path*', testRouteHandler)
router.get('/thrustmaster-:path*', testRouteHandler)
router.get('/topaz-:path*', testRouteHandler)
router.get('/topsku-:path*', testRouteHandler)
router.get('/transcend-:path*', testRouteHandler)
router.get('/tritton-:path*', testRouteHandler)
router.get('/ttx-tech-:path*', testRouteHandler)
router.get('/rotolight-:path*', testRouteHandler)
router.get('/sabrent-:path*', testRouteHandler)
router.get('/saddle-:path*', testRouteHandler)
router.get('/sapphire-:path*', testRouteHandler)
router.get('/satellite-:path*', testRouteHandler)
router.get('/sbig-:path*', testRouteHandler)
router.get('/schiit-:path*', testRouteHandler)
router.get('/schneider-kreuznach-:path*', testRouteHandler)
router.get('/se-:path*', testRouteHandler)
router.get('/sears-:path*', testRouteHandler)
router.get('/seasonic-:path*', testRouteHandler)
router.get('/sedna-:path*', testRouteHandler)
router.get('/seed-:path*', testRouteHandler)
router.get('/sega-:path*', testRouteHandler)
router.get('/segate-:path*', testRouteHandler)
router.get('/sentri-:path*', testRouteHandler)
router.get('/sharkk-:path*', testRouteHandler)
router.get('/sharp-:path*', testRouteHandler)
router.get('/sierra-wireless-:path*', testRouteHandler)
router.get('/silicondust-:path*', testRouteHandler)
router.get('/sillicondust-:path*', testRouteHandler)
router.get('/silvertone-:path*', testRouteHandler)
router.get('/sima-:path*', testRouteHandler)
router.get('/sk-hyinx-:path*', testRouteHandler)
router.get('/skhynix-korea-:path*', testRouteHandler)
router.get('/slingbox-:path*', testRouteHandler)
router.get('/solaris-audio-:path*', testRouteHandler)
router.get('/solo-:path*', testRouteHandler)
router.get('/sonicwall-:path*', testRouteHandler)
router.get('/owc-:path*', testRouteHandler)
router.get('/panamax-:path*', testRouteHandler)
router.get('/peavey-:path*', testRouteHandler)
router.get('/pelican-:path*', testRouteHandler)
router.get('/penguin-:path*', testRouteHandler)
router.get('/planar-:path*', testRouteHandler)
router.get('/playstation-:path*', testRouteHandler)
router.get('/poland-:path*', testRouteHandler)
router.get('/posturite-:path*', testRouteHandler)
router.get('/powercolor-:path*', testRouteHandler)
router.get('/powerspec-:path*', testRouteHandler)
router.get('/produplicator-:path*', testRouteHandler)
router.get('/pyle-audio-:path*', testRouteHandler)
router.get('/pyle-pro-:path*', testRouteHandler)
router.get('/qsc-:path*', testRouteHandler)
router.get('/quiksilver-:path*', testRouteHandler)
router.get('/radeon-:path*', testRouteHandler)
router.get('/radio-shack-:path*', testRouteHandler)
router.get('/raidmax-:path*', testRouteHandler)
router.get('/rain-design-:path*', testRouteHandler)
router.get('/raspberry-pi-:path*', testRouteHandler)
router.get('/realistic-:path*', testRouteHandler)
router.get('/rebbic-:path*', testRouteHandler)
router.get('/red-:path*', testRouteHandler)
router.get('/revolabs-:path*', testRouteHandler)
router.get('/ricoh-:path*', testRouteHandler)
router.get('/roccat-:path*', testRouteHandler)
router.get('/rode-:path*', testRouteHandler)
router.get('/roku-:path*', testRouteHandler)
router.get('/moog-:path*', testRouteHandler)
router.get('/mota-:path*', testRouteHandler)
router.get('/mushkin-:path*', testRouteHandler)
router.get('/musicman-:path*', testRouteHandler)
router.get('/nanya-:path*', testRouteHandler)
router.get('/nasum-:path*', testRouteHandler)
router.get('/national-:path*', testRouteHandler)
router.get('/nave-point-:path*', testRouteHandler)
router.get('/neat-:path*', testRouteHandler)
router.get('/neewer-:path*', testRouteHandler)
router.get('/nest-:path*', testRouteHandler)
router.get('/nmb-:path*', testRouteHandler)
router.get('/noctua-:path*', testRouteHandler)
router.get('/northern-:path*', testRouteHandler)
router.get('/northstar-:path*', testRouteHandler)
router.get('/nyko-:path*', testRouteHandler)
router.get('/obinslab-:path*', testRouteHandler)
router.get('/ocz-:path*', testRouteHandler)
router.get('/on-stage-:path*', testRouteHandler)
router.get('/onn-:path*', testRouteHandler)
router.get('/opin-:path*', testRouteHandler)
router.get('/orange-crush-:path*', testRouteHandler)
router.get('/orico-:path*', testRouteHandler)
router.get('/orion-fans-:path*', testRouteHandler)
router.get('/otter-box-:path*', testRouteHandler)
router.get('/leelbox-:path*', testRouteHandler)
router.get('/lepa-:path*', testRouteHandler)
router.get('/li-shin-international-enterprise-corp-:path*', testRouteHandler)
router.get('/lifesize-:path*', testRouteHandler)
router.get('/liftmaster-:path*', testRouteHandler)
router.get('/line-6-:path*', testRouteHandler)
router.get('/linktropy-:path*', testRouteHandler)
router.get('/livescribe-:path*', testRouteHandler)
router.get('/logan-:path*', testRouteHandler)
router.get('/m-audio-:path*', testRouteHandler)
router.get('/m-edge-:path*', testRouteHandler)
router.get('/macbook-:path*', testRouteHandler)
router.get('/mackie-:path*', testRouteHandler)
router.get('/magellan-:path*', testRouteHandler)
router.get('/magtek-:path*', testRouteHandler)
router.get('/malwarebytes-:path*', testRouteHandler)
router.get('/manfrotto-:path*', testRouteHandler)
router.get('/manhattan-:path*', testRouteHandler)
router.get('/maxell-:path*', testRouteHandler)
router.get('/maxwell-:path*', testRouteHandler)
router.get('/mda-:path*', testRouteHandler)
router.get('/micomsoft-:path*', testRouteHandler)
router.get('/micronta-:path*', testRouteHandler)
router.get('/middle-atlantic-:path*', testRouteHandler)
router.get('/mionix-:path*', testRouteHandler)
router.get('/monoprice-:path*', testRouteHandler)
router.get('/monster-:path*', testRouteHandler)
router.get('/monster-power-:path*', testRouteHandler)
router.get('/ifs-:path*', testRouteHandler)
router.get('/ikan-:path*', testRouteHandler)
router.get('/impact-:path*', testRouteHandler)
router.get('/imxw-:path*', testRouteHandler)
router.get('/inateck-:path*', testRouteHandler)
router.get('/infocus-:path*', testRouteHandler)
router.get('/innolux-:path*', testRouteHandler)
router.get('/interlogix-:path*', testRouteHandler)
router.get('/intermec-:path*', testRouteHandler)
router.get('/intertek-:path*', testRouteHandler)
router.get('/iomega-ego-:path*', testRouteHandler)
router.get('/ion-:path*', testRouteHandler)
router.get('/iskn-:path*', testRouteHandler)
router.get('/istarusa-:path*', testRouteHandler)
router.get('/iz3d-:path*', testRouteHandler)
router.get('/j-w-davis-:path*', testRouteHandler)
router.get('/jabra-:path*', testRouteHandler)
router.get('/jackery-:path*', testRouteHandler)
router.get('/janam-:path*', testRouteHandler)
router.get('/joy-factory-:path*', testRouteHandler)
router.get('/kate-spade-:path*', testRouteHandler)
router.get('/kemp-technologies-:path*', testRouteHandler)
router.get('/killer-:path*', testRouteHandler)
router.get('/klein-tools-:path*', testRouteHandler)
router.get('/klevv-:path*', testRouteHandler)
router.get('/landingzone-:path*', testRouteHandler)
router.get('/furman-:path*', testRouteHandler)
router.get('/gamer-storm-:path*', testRouteHandler)
router.get('/gamestergear-:path*', testRouteHandler)
router.get('/garmin-:path*', testRouteHandler)
router.get('/gear-head-:path*', testRouteHandler)
router.get('/gearhead-:path*', testRouteHandler)
router.get('/geil-:path*', testRouteHandler)
router.get('/generic-:path*', testRouteHandler)
router.get('/gogroove-:path*', testRouteHandler)
router.get('/goldtouch-:path*', testRouteHandler)
router.get('/green-hills-:path*', testRouteHandler)
router.get('/griffin-:path*', testRouteHandler)
router.get('/gsc-:path*', testRouteHandler)
router.get('/harman-:path*', testRouteHandler)
router.get('/harman-kardon-:path*', testRouteHandler)
router.get('/henge-docks-:path*', testRouteHandler)
router.get('/hewlett-packard-:path*', testRouteHandler)
router.get('/hexin-technology-:path*', testRouteHandler)
router.get('/hgst-:path*', testRouteHandler)
router.get('/hippus-:path*', testRouteHandler)
router.get('/his-:path*', testRouteHandler)
router.get('/huion-:path*', testRouteHandler)
router.get('/hyperdrive-:path*', testRouteHandler)
router.get('/hyperx-:path*', testRouteHandler)
router.get('/delphi-:path*', testRouteHandler)
router.get('/delta-electronics-:path*', testRouteHandler)
router.get('/devention-:path*', testRouteHandler)
router.get('/digital-check-:path*', testRouteHandler)
router.get('/digium-:path*', testRouteHandler)
router.get('/discovery-kids-:path*', testRouteHandler)
router.get('/display-link-:path*', testRouteHandler)
router.get('/dremel-:path*', testRouteHandler)
router.get('/dxt-:path*', testRouteHandler)
router.get('/dymo-:path*', testRouteHandler)
router.get('/e-element-:path*', testRouteHandler)
router.get('/eagle-:path*', testRouteHandler)
router.get('/eartec-:path*', testRouteHandler)
router.get('/ecoplus-:path*', testRouteHandler)
router.get('/edimax-:path*', testRouteHandler)
router.get('/eero-:path*', testRouteHandler)
router.get('/eico-:path*', testRouteHandler)
router.get('/eluktronics-:path*', testRouteHandler)
router.get('/energy-:path*', testRouteHandler)
router.get('/ergotron-:path*', testRouteHandler)
router.get('/extreme-networks-:path*', testRouteHandler)
router.get('/ezviz-:path*', testRouteHandler)
router.get('/firepro-graphics-:path*', testRouteHandler)
router.get('/firstinnovation-:path*', testRouteHandler)
router.get('/brydge-:path*', testRouteHandler)
router.get('/buffalo-:path*', testRouteHandler)
router.get('/bushnell-:path*', testRouteHandler)
router.get('/cambridge-:path*', testRouteHandler)
router.get('/camgeeker-:path*', testRouteHandler)
router.get('/canary-:path*', testRouteHandler)
router.get('/casio-:path*', testRouteHandler)
router.get('/cat-:path*', testRouteHandler)
router.get('/cendyne-:path*', testRouteHandler)
router.get('/cherry-:path*', testRouteHandler)
router.get('/chimei-innolux-:path*', testRouteHandler)
router.get('/cirago-:path*', testRouteHandler)
router.get('/clazio-:path*', testRouteHandler)
router.get('/cocoon-:path*', testRouteHandler)
router.get('/cognex-:path*', testRouteHandler)
router.get('/compaq-:path*', testRouteHandler)
router.get('/crestron-:path*', testRouteHandler)
router.get('/crown-:path*', testRouteHandler)
router.get('/crucial-:path*', testRouteHandler)
router.get('/cryorig-:path*', testRouteHandler)
router.get('/custom-:path*', testRouteHandler)
router.get('/cyberpower-:path*', testRouteHandler)
router.get('/das-keyboard-:path*', testRouteHandler)
router.get('/datto-alto-:path*', testRouteHandler)
router.get('/dbx-286s-:path*', testRouteHandler)
router.get('/delkin-:path*', testRouteHandler)
router.get('/artic-:path*', testRouteHandler)
router.get('/as-rock-:path*', testRouteHandler)
router.get('/asiyun-:path*', testRouteHandler)
router.get('/au-optronics-:path*', testRouteHandler)
router.get('/audio-technica-:path*', testRouteHandler)
router.get('/aver-media-:path*', testRouteHandler)
router.get('/avermedia-:path*', testRouteHandler)
router.get('/avexir-:path*', testRouteHandler)
router.get('/avocent-:path*', testRouteHandler)
router.get('/axiom-:path*', testRouteHandler)
router.get('/axler-:path*', testRouteHandler)
router.get('/azur-:path*', testRouteHandler)
router.get('/ballistix-:path*', testRouteHandler)
router.get('/battery-biz-1-:path*', testRouteHandler)
router.get('/battery-biz-:path*', testRouteHandler)
router.get('/bescor-:path*', testRouteHandler)
router.get('/biamp-:path*', testRouteHandler)
router.get('/biostar-:path*', testRouteHandler)
router.get('/blackmagic-design-:path*', testRouteHandler)
router.get('/blink-:path*', testRouteHandler)
router.get('/blitzwolf-:path*', testRouteHandler)
router.get('/blue-:path*', testRouteHandler)
router.get('/bosch-:path*', testRouteHandler)
router.get('/boss-:path*', testRouteHandler)
router.get('/boxx-:path*', testRouteHandler)
router.get('/brookstone-:path*', testRouteHandler)
router.get('/behringer-:path*', testRouteHandler)
router.get('/kinesis-coperation-:path*', testRouteHandler)
router.get('/onkyo-:path*', testRouteHandler)
router.get('/sengled-:path*', testRouteHandler)
router.get('/vanguard-:path*', testRouteHandler)
router.get('/3com-:path*', testRouteHandler)
router.get('/3d-connections-:path*', testRouteHandler)
router.get('/3dconnexion-:path*', testRouteHandler)
router.get('/4-all-memory-:path*', testRouteHandler)
router.get('/abit-:path*', testRouteHandler)
router.get('/ac-infinity-:path*', testRouteHandler)
router.get('/acti-:path*', testRouteHandler)
router.get('/adamanta-:path*', testRouteHandler)
router.get('/adata-:path*', testRouteHandler)
router.get('/adtran-:path*', testRouteHandler)
router.get('/air-mouse-:path*', testRouteHandler)
router.get('/aja-:path*', testRouteHandler)
router.get('/ajoka-:path*', testRouteHandler)
router.get('/akg-:path*', testRouteHandler)
router.get('/alienware-:path*', testRouteHandler)
router.get('/ambiq-micro-:path*', testRouteHandler)
router.get('/applied-research-and-technology-:path*', testRouteHandler)
router.get('/apposite-technologies-:path*', testRouteHandler)
router.get('/arch-:path*', testRouteHandler)
router.get('/aroma-:path*', testRouteHandler)
router.get('/yamaha-:path*', testRouteHandler)
router.get('/yashica-:path*', testRouteHandler)
router.get('/yuneec-:path*', testRouteHandler)
router.get('/zte-:path*', testRouteHandler)
router.get('/zyxel-:path*', testRouteHandler)
router.get('/ultimate-ears-:path*', testRouteHandler)
router.get('/univox-:path*', testRouteHandler)
router.get('/v%252dmoda-:path*', testRouteHandler)
router.get('/verizon-:path*', testRouteHandler)
router.get('/vibra-:path*', testRouteHandler)
router.get('/viewsonic-:path*', testRouteHandler)
router.get('/viotek-:path*', testRouteHandler)
router.get('/vivotek-:path*', testRouteHandler)
router.get('/vizio-:path*', testRouteHandler)
router.get('/wacom-:path*', testRouteHandler)
router.get('/walkera-:path*', testRouteHandler)
router.get('/welch-allyn-:path*', testRouteHandler)
router.get('/western-digital-:path*', testRouteHandler)
router.get('/wind-wing-:path*', testRouteHandler)
router.get('/wt-:path*', testRouteHandler)
router.get('/xerox-:path*', testRouteHandler)
router.get('/xfx-:path*', testRouteHandler)
router.get('/southwire-:path*', testRouteHandler)
router.get('/sp360_4k%252dbk5-:path*', testRouteHandler)
router.get('/speco-:path*', testRouteHandler)
router.get('/stanley-:path*', testRouteHandler)
router.get('/starry-:path*', testRouteHandler)
router.get('/startech-:path*', testRouteHandler)
router.get('/starview-:path*', testRouteHandler)
router.get('/steel-:path*', testRouteHandler)
router.get('/steelie-:path*', testRouteHandler)
router.get('/steelseries-:path*', testRouteHandler)
router.get('/suplet-:path*', testRouteHandler)
router.get('/suprema-:path*', testRouteHandler)
router.get('/t.b.-vegas-:path*', testRouteHandler)
router.get('/targus-:path*', testRouteHandler)
router.get('/tascam-:path*', testRouteHandler)
router.get('/teac-:path*', testRouteHandler)
router.get('/techsquid-:path*', testRouteHandler)
router.get('/texas-instruments-:path*', testRouteHandler)
router.get('/thermaltake-:path*', testRouteHandler)
router.get('/thule-:path*', testRouteHandler)
router.get('/toshiba-:path*', testRouteHandler)
router.get('/tp%252dlink-:path*', testRouteHandler)
router.get('/traxxas-:path*', testRouteHandler)
router.get('/trendnet-:path*', testRouteHandler)
router.get('/tripp-lite-:path*', testRouteHandler)
router.get('/ubiquiti-:path*', testRouteHandler)
router.get('/udi-r%7b47%7dc-:path*', testRouteHandler)
router.get('/ue%252droll-:path*', testRouteHandler)
router.get('/rosewill-:path*', testRouteHandler)
router.get('/rosslare-:path*', testRouteHandler)
router.get('/rubermaid-:path*', testRouteHandler)
router.get('/russound-:path*', testRouteHandler)
router.get('/ryobi-:path*', testRouteHandler)
router.get('/saitek-:path*', testRouteHandler)
router.get('/samson-:path*', testRouteHandler)
router.get('/samsung-:path*', testRouteHandler)
router.get('/sandisk-:path*', testRouteHandler)
router.get('/sato-:path*', testRouteHandler)
router.get('/seagate-:path*', testRouteHandler)
router.get('/sennheiser-:path*', testRouteHandler)
router.get('/sharper-image-:path*', testRouteHandler)
router.get('/sherwood-:path*', testRouteHandler)
router.get('/shure-:path*', testRouteHandler)
router.get('/siig-:path*', testRouteHandler)
router.get('/skhynix-:path*', testRouteHandler)
router.get('/smc-networks-:path*', testRouteHandler)
router.get('/snark-:path*', testRouteHandler)
router.get('/sonos-:path*', testRouteHandler)
router.get('/sony-:path*', testRouteHandler)
router.get('/panasonic-:path*', testRouteHandler)
router.get('/paradigm-:path*', testRouteHandler)
router.get('/patriot-:path*', testRouteHandler)
router.get('/patroleyes-:path*', testRouteHandler)
router.get('/pc-power-%26-cooling-:path*', testRouteHandler)
router.get('/philips-:path*', testRouteHandler)
router.get('/pilot-automotive-:path*', testRouteHandler)
router.get('/pioneer-:path*', testRouteHandler)
router.get('/planet-:path*', testRouteHandler)
router.get('/plantronics-:path*', testRouteHandler)
router.get('/pny-:path*', testRouteHandler)
router.get('/polycom-:path*', testRouteHandler)
router.get('/powersonic-:path*', testRouteHandler)
router.get('/promaster-:path*', testRouteHandler)
router.get('/prudent-way-:path*', testRouteHandler)
router.get('/radiant-:path*', testRouteHandler)
router.get('/razer-:path*', testRouteHandler)
router.get('/rca-:path*', testRouteHandler)
router.get('/rhino%252drack-:path*', testRouteHandler)
router.get('/rim-blackberry-:path*', testRouteHandler)
router.get('/ring-:path*', testRouteHandler)
router.get('/motion-:path*', testRouteHandler)
router.get('/motorola-:path*', testRouteHandler)
router.get('/msi-:path*', testRouteHandler)
router.get('/navdy-:path*', testRouteHandler)
router.get('/nec-:path*', testRouteHandler)
router.get('/neopost-:path*', testRouteHandler)
router.get('/netgear-:path*', testRouteHandler)
router.get('/nextar-:path*', testRouteHandler)
router.get('/night-owl-:path*', testRouteHandler)
router.get('/nikon-:path*', testRouteHandler)
router.get('/niles-:path*', testRouteHandler)
router.get('/nintendo-:path*', testRouteHandler)
router.get('/nixeus-:path*', testRouteHandler)
router.get('/nokia-:path*', testRouteHandler)
router.get('/nuuo-:path*', testRouteHandler)
router.get('/nuvision-:path*', testRouteHandler)
router.get('/nvidia-:path*', testRouteHandler)
router.get('/oculus-:path*', testRouteHandler)
router.get('/oki-:path*', testRouteHandler)
router.get('/olympus-:path*', testRouteHandler)
router.get('/oneplus-:path*', testRouteHandler)
router.get('/onkyo-:path*', testRouteHandler)
router.get('/opti%252dtekscope-:path*', testRouteHandler)
router.get('/other-:path*', testRouteHandler)
router.get('/otterbox-:path*', testRouteHandler)
router.get('/learnpad-:path*', testRouteHandler)
router.get('/lenovo-:path*', testRouteHandler)
router.get('/lexar-:path*', testRouteHandler)
router.get('/lg-:path*', testRouteHandler)
router.get('/lind-electronics-:path*', testRouteHandler)
router.get('/linksys-:path*', testRouteHandler)
router.get('/lite%252don-:path*', testRouteHandler)
router.get('/lix-:path*', testRouteHandler)
router.get('/logisys-:path*', testRouteHandler)
router.get('/logitech-:path*', testRouteHandler)
router.get('/lts-:path*', testRouteHandler)
router.get('/luxul-:path*', testRouteHandler)
router.get('/lynec-:path*', testRouteHandler)
router.get('/macally-:path*', testRouteHandler)
router.get('/marantz-:path*', testRouteHandler)
router.get('/march-networks-:path*', testRouteHandler)
router.get('/martian-watches-:path*', testRouteHandler)
router.get('/mcdermott-:path*', testRouteHandler)
router.get('/meraki-:path*', testRouteHandler)
router.get('/micron-:path*', testRouteHandler)
router.get('/microsoft-:path*', testRouteHandler)
router.get('/molex-:path*', testRouteHandler)
router.get('/icy-dock-:path*', testRouteHandler)
router.get('/ifrogz-:path*', testRouteHandler)
router.get('/ihome-:path*', testRouteHandler)
router.get('/incase-:path*', testRouteHandler)
router.get('/incipio-:path*', testRouteHandler)
router.get('/inland-:path*', testRouteHandler)
router.get('/insteon-:path*', testRouteHandler)
router.get('/intel-:path*', testRouteHandler)
router.get('/iogear-:path*', testRouteHandler)
router.get('/j5-create-:path*', testRouteHandler)
router.get('/jbl-:path*', testRouteHandler)
router.get('/jlab-:path*', testRouteHandler)
router.get('/jvc-:path*', testRouteHandler)
router.get('/jwin-:path*', testRouteHandler)
router.get('/kantech-:path*', testRouteHandler)
router.get('/kensington-:path*', testRouteHandler)
router.get('/kingston-:path*', testRouteHandler)
router.get('/klipsch-:path*', testRouteHandler)
router.get('/kodak-:path*', testRouteHandler)
router.get('/konftel-:path*', testRouteHandler)
router.get('/korg-:path*', testRouteHandler)
router.get('/kyocera-:path*', testRouteHandler)
router.get('/lacie-:path*', testRouteHandler)
router.get('/latitude-:path*', testRouteHandler)
router.get('/foxconn-:path*', testRouteHandler)
router.get('/fujifilm-:path*', testRouteHandler)
router.get('/fujitsu-:path*', testRouteHandler)
router.get('/g%252dtechnology-:path*', testRouteHandler)
router.get('/g.skill-:path*', testRouteHandler)
router.get('/gateway-:path*', testRouteHandler)
router.get('/gefen-:path*', testRouteHandler)
router.get('/gen-x-:path*', testRouteHandler)
router.get('/genesis-:path*', testRouteHandler)
router.get('/geo-vision-:path*', testRouteHandler)
router.get('/gigabyte-:path*', testRouteHandler)
router.get('/giotech-:path*', testRouteHandler)
router.get('/glyph-:path*', testRouteHandler)
router.get('/goldstar-:path*', testRouteHandler)
router.get('/google-:path*', testRouteHandler)
router.get('/gopro-:path*', testRouteHandler)
router.get('/havis-:path*', testRouteHandler)
router.get('/henge-:path*', testRouteHandler)
router.get('/hikvision-:path*', testRouteHandler)
router.get('/hitachi-:path*', testRouteHandler)
router.get('/honeywell-:path*', testRouteHandler)
router.get('/hp-:path*', testRouteHandler)
router.get('/htc-:path*', testRouteHandler)
router.get('/hubsan-:path*', testRouteHandler)
router.get('/hynix-:path*', testRouteHandler)
router.get('/ibm-:path*', testRouteHandler)
router.get('/denon-:path*', testRouteHandler)
router.get('/dewalt-:path*', testRouteHandler)
router.get('/diamond-:path*', testRouteHandler)
router.get('/discount-electronics-:path*', testRouteHandler)
router.get('/dji-:path*', testRouteHandler)
router.get('/dolby-:path*', testRouteHandler)
router.get('/drobo-:path*', testRouteHandler)
router.get('/dual-:path*', testRouteHandler)
router.get('/dynavox-:path*', testRouteHandler)
router.get('/ecs-:path*', testRouteHandler)
router.get('/edugear-:path*', testRouteHandler)
router.get('/ekwb-:path*', testRouteHandler)
router.get('/elgato-:path*', testRouteHandler)
router.get('/elo-:path*', testRouteHandler)
router.get('/emachines-:path*', testRouteHandler)
router.get('/enermax-:path*', testRouteHandler)
router.get('/engenius-:path*', testRouteHandler)
router.get('/episode-:path*', testRouteHandler)
router.get('/epson-:path*', testRouteHandler)
router.get('/everlasting-:path*', testRouteHandler)
router.get('/evga-:path*', testRouteHandler)
router.get('/ez-fly-rc-:path*', testRouteHandler)
router.get('/filco-:path*', testRouteHandler)
router.get('/fitbit-:path*', testRouteHandler)
router.get('/focusrite-:path*', testRouteHandler)
router.get('/foscam-:path*', testRouteHandler)
router.get('/brother-:path*', testRouteHandler)
router.get('/built-ny-:path*', testRouteHandler)
router.get('/bytec-:path*', testRouteHandler)
router.get('/caldigit-:path*', testRouteHandler)
router.get('/canon-:path*', testRouteHandler)
router.get('/case-logic-:path*', testRouteHandler)
router.get('/cdvi-:path*', testRouteHandler)
router.get('/chatsworth-:path*', testRouteHandler)
router.get('/chenbro-:path*', testRouteHandler)
router.get('/christie-:path*', testRouteHandler)
router.get('/cisco-:path*', testRouteHandler)
router.get('/cobra-:path*', testRouteHandler)
router.get('/coby-:path*', testRouteHandler)
router.get('/colorgraphic-:path*', testRouteHandler)
router.get('/consoletuner-:path*', testRouteHandler)
router.get('/cooler-master-:path*', testRouteHandler)
router.get('/corsair-:path*', testRouteHandler)
router.get('/cosmicar-:path*', testRouteHandler)
router.get('/cotytech-:path*', testRouteHandler)
router.get('/creative-:path*', testRouteHandler)
router.get('/creative-labs-:path*', testRouteHandler)
router.get('/d%252dlink-:path*', testRouteHandler)
router.get('/definitive-technology-:path*', testRouteHandler)
router.get('/dell-:path*', testRouteHandler)
router.get('/arris-:path*', testRouteHandler)
router.get('/aruba-networks-:path*', testRouteHandler)
router.get('/asrock-:path*', testRouteHandler)
router.get('/asus-:path*', testRouteHandler)
router.get('/at%26t-:path*', testRouteHandler)
router.get('/ati-:path*', testRouteHandler)
router.get('/austone-:path*', testRouteHandler)
router.get('/austone-electronics-:path*', testRouteHandler)
router.get('/avast-:path*', testRouteHandler)
router.get('/avaya-:path*', testRouteHandler)
router.get('/axis-:path*', testRouteHandler)
router.get('/azulle-:path*', testRouteHandler)
router.get('/bang-%26-olufsen-:path*', testRouteHandler)
router.get('/barnes-%26-noble-:path*', testRouteHandler)
router.get('/barracuda-:path*', testRouteHandler)
router.get('/beats-:path*', testRouteHandler)
router.get('/behringer-:path*', testRouteHandler)
router.get('/belkin-:path*', testRouteHandler)
router.get('/benq-:path*', testRouteHandler)
router.get('/bio%252dkey-:path*', testRouteHandler)
router.get('/blackberry-:path*', testRouteHandler)
router.get('/bose-:path*', testRouteHandler)
router.get('/bravo-view-:path*', testRouteHandler)
router.get('/brenthaven-:path*', testRouteHandler)
router.get('/6830s-:path*', testRouteHandler)
router.get('/acer-:path*', testRouteHandler)
router.get('/acti-corp-:path*', testRouteHandler)
router.get('/actiontec-:path*', testRouteHandler)
router.get('/adaptec-:path*', testRouteHandler)
router.get('/adcom-:path*', testRouteHandler)
router.get('/adp-:path*', testRouteHandler)
router.get('/aftermarket-:path*', testRouteHandler)
router.get('/airlink-:path*', testRouteHandler)
router.get('/aiwa-:path*', testRouteHandler)
router.get('/akai-:path*', testRouteHandler)
router.get('/alesis-:path*', testRouteHandler)
router.get('/alibi-:path*', testRouteHandler)
router.get('/altec-lansing-:path*', testRouteHandler)
router.get('/altigen-:path*', testRouteHandler)
router.get('/aluratek-:path*', testRouteHandler)
router.get('/amazon-:path*', testRouteHandler)
router.get('/amd-:path*', testRouteHandler)
router.get('/amped-:path*', testRouteHandler)
router.get('/amped-wireless-:path*', testRouteHandler)
router.get('/antec-:path*', testRouteHandler)
router.get('/aoc-:path*', testRouteHandler)
router.get('/apc-:path*', testRouteHandler)
router.get('/apple-:path*', testRouteHandler)
router.get('/arecont-:path*', testRouteHandler)
/**
 * Pages: other
 */
router.get('/locations/:path*', testRouteHandler)
router.get('/email-us/:path*', testRouteHandler)
router.get('/news/:path*', testRouteHandler)
router.get('/contact/:path*', testRouteHandler)
router.get('/sitemap/:path*', testRouteHandler)
router.get('/recycling/:path*', testRouteHandler)
router
  .get('/business-:path*', testRouteHandler)
  .use(nextRoutes)
  .fallback(({ redirect }) => {
    return redirect('/', 302)
  })

module.exports = router
