post:
  tags:
    - configs
  summary: Deploy Edge Configuration on environment
  description: Replace and deploy a complete edge configuration for the given environment
  operationId: postConfigV01Configs
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/postConfigV01Configs.yaml
    required: true
  responses:
    '202':
      description: >-
        Replace and deploy a complete edge configuration for the given
        environment
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Config_V1_Entities_Config.yaml
    '400':
      description: UserError
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '404':
      description: RecordNotFound
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '500':
      description: ServerError
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
  x-codegen-request-body-name: postConfigV01Configs
