get:
  tags:
    - deployments
  summary: Read deployment
  description: Read deployment
  operationId: getConfigV01DeploymentsDeploymentId
  parameters:
    - name: deployment_id
      in: path
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Read deployment
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Config_V1_Entities_Deployment.yaml
    '400':
      description: UserError
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '404':
      description: RecordNotFound
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '500':
      description: ServerError
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
