put:
  summary: Set Bulk Redirect
  description: Creates or updates a bulk redirect.
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/putConfigV01EnvironmentRedirects.yaml
    required: true
  security:
    - configScope:
        - app.config
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Config_V1_Entities_EnvironmentRedirect.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_Error_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/BaseApi_Entities_Error_UnauthorizedError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_Error_ForbiddenError.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/BaseApi_Entities_Error_RecordNotFoundError.yaml
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/BaseApi_Entities_Error_TooManyRequestsError.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_Error_ServerError.yaml
  tags:
    - environment-redirects
  operationId: putConfigV01EnvironmentRedirects
get:
  summary: Get All Bulk Redirects
  description: Returns all bulk redirects associated with an environment.
  parameters:
    - in: query
      name: page
      description: 0-based page number.
      required: false
      schema:
        type: integer
        format: int32
        default: 0
    - in: query
      name: page_size
      description: >-
        Number of results per page. Valid values are: 1 - 100. **Default
        value:** 20
      required: false
      schema:
        type: integer
        format: int32
        default: 20
    - in: query
      name: from
      description: Find a bulk redirect by its source URL (`from`).
      required: false
      schema:
        type: string
    - in: query
      name: environment_id
      description: >
        An environment's system-defined ID (e.g.,
        12345678-1234-1234-1234-1234567890ab).


        From the Edgio Console, navigate to the desired environment and then
        click **Settings**. It is listed under **Environment ID**.
      required: true
      schema:
        type: string
  security:
    - configScope:
        - app.config
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/Config_V1_Entities_EnvironmentRedirect_Collection.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_Error_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/BaseApi_Entities_Error_UnauthorizedError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_Error_ForbiddenError.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/BaseApi_Entities_Error_RecordNotFoundError.yaml
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/BaseApi_Entities_Error_TooManyRequestsError.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_Error_ServerError.yaml
  tags:
    - environment-redirects
  operationId: getConfigV01EnvironmentRedirects
