export default [
  // existing redirects (may be outdated)
  ['/guides/starter', '/guides/traditional_sites'],
  ['/guides/debugging', '/guides/troubleshooting'],
  ['/guides/deploying', '/guides/deploy_apps'],
  ['/guides/getting_started', '/guides/build_web_apps'],

  // sidenav changes
  ['/guides/webapp_cdn_getting_started', '/guides/getting_started_performance'],
  ['/guides/deploy_apps', '/guides/basics/deploy_apps'],
  ['/guides/edgio_config', '/guides/basics/edgio_config'],
  ['/guides/environments', '/guides/basics/environments'],
  ['/guides/production', '/guides/basics/production'],
  ['/guides/teams', '/guides/basics/teams'],
  ['/guides/cli', '/guides/develop/cli'],
  ['/guides/deploy_to_edgio', '/guides/develop/deploy_to_edgio'],
  ['/guides/logs', '/guides/develop/logs'],
  ['/guides/packages', '/guides/develop/packages'],
  ['/guides/rest_api', '/guides/develop/rest_api'],
  ['/guides/bigcommerce', '/guides/integrations/bigcommerce'],
  ['/guides/bloomreach', '/guides/integrations/bloomreach'],
  ['/guides/shopify_hydrogen', '/guides/integrations/shopify_hydrogen'],
  ['/guides/swell', '/guides/integrations/swell'],
  ['/guides/wordpress', '/guides/integrations/wordpress'],
  ['/guides/caching', '/guides/performance/caching'],
  ['/guides/compression', '/guides/performance/compression'],
  ['/guides/edgejs_testing', '/guides/performance/edgejs_testing'],
  [
    '/guides/getting_started_performance',
    '/guides/performance/getting_started_performance',
  ],
  ['/guides/graphql', '/guides/performance/graphql'],
  ['/guides/image_optimization', '/guides/performance/image_optimization'],
  ['/guides/observability', '/guides/performance/observability'],
  [
    '/guides/core_web_vitals',
    '/guides/performance/observability/core_web_vitals',
  ],
  ['/guides/devtools', '/guides/performance/observability/devtools'],
  ['/guides/prefetching', '/guides/performance/prefetching'],
  ['/guides/purging', '/guides/performance/purging'],
  ['/guides/request_headers', '/guides/performance/request_headers'],
  ['/guides/response_headers', '/guides/performance/response_headers'],
  ['/guides/routing', '/guides/performance/routing'],
  ['/guides/serverless_functions', '/guides/performance/serverless_functions'],
  ['/guides/third_party_cdns', '/guides/performance/third_party_cdns'],
  ['/guides/traffic_splitting', '/guides/performance/traffic_splitting'],
  [
    '/guides/split_testing',
    '/guides/performance/traffic_splitting/split_testing',
  ],
  ['/guides/layer0_migration', '/guides/reference/layer0_migration'],
  ['/guides/saml', '/guides/reference/saml'],
  ['/guides/v5_migration', '/guides/reference/v5_migration'],
  ['/guides/managed_rule_groups', '/guides/security/managed_rule_groups'],
  ['/guides/security_suite', '/guides/security/security_suite'],
  ['/guides/connectors', '/guides/sites_frameworks/connectors'],
  ['/guides/isg', '/guides/sites_frameworks/isg'],
  [
    '/guides/jamstack_getting_started',
    '/guides/sites_frameworks/getting_started',
  ],
  ['/guides/angular', '/guides/sites_frameworks/getting_started/angular'],
  ['/guides/astro', '/guides/sites_frameworks/getting_started/astro'],
  ['/guides/brunch', '/guides/sites_frameworks/getting_started/brunch'],
  ['/guides/docusaurus', '/guides/sites_frameworks/getting_started/docusaurus'],
  ['/guides/dojo', '/guides/sites_frameworks/getting_started/dojo'],
  ['/guides/eleventy', '/guides/sites_frameworks/getting_started/eleventy'],
  ['/guides/ember', '/guides/sites_frameworks/getting_started/ember'],
  [
    '/guides/ember_fastboot',
    '/guides/sites_frameworks/getting_started/ember_fastboot',
  ],
  ['/guides/express', '/guides/sites_frameworks/getting_started/express'],
  ['/guides/frontity', '/guides/sites_frameworks/getting_started/frontity'],
  ['/guides/gatsby', '/guides/sites_frameworks/getting_started/gatsby'],
  ['/guides/gridsome', '/guides/sites_frameworks/getting_started/gridsome'],
  ['/guides/hexo', '/guides/sites_frameworks/getting_started/hexo'],
  ['/guides/hugo', '/guides/sites_frameworks/getting_started/hugo'],
  [
    '/guides/ionic_react',
    '/guides/sites_frameworks/getting_started/ionic_react',
  ],
  ['/guides/ionic_vue', '/guides/sites_frameworks/getting_started/ionic_vue'],
  ['/guides/jekyll', '/guides/sites_frameworks/getting_started/jekyll'],
  ['/guides/lit', '/guides/sites_frameworks/getting_started/lit'],
  ['/guides/mkdocs', '/guides/sites_frameworks/getting_started/mkdocs'],
  ['/guides/next', '/guides/sites_frameworks/getting_started/next'],
  [
    '/guides/next_commerce',
    '/guides/sites_frameworks/getting_started/next_commerce',
  ],
  ['/guides/nuxt', '/guides/sites_frameworks/getting_started/nuxt'],
  ['/guides/nuxt3', '/guides/sites_frameworks/getting_started/nuxt3'],
  ['/guides/nx', '/guides/sites_frameworks/getting_started/nx'],
  ['/guides/preact', '/guides/sites_frameworks/getting_started/preact'],
  ['/guides/razzle', '/guides/sites_frameworks/getting_started/razzle'],
  [
    '/guides/react-storefront',
    '/guides/sites_frameworks/getting_started/react-storefront',
  ],
  ['/guides/react', '/guides/sites_frameworks/getting_started/react'],
  [
    '/guides/react_static',
    '/guides/sites_frameworks/getting_started/react_static',
  ],
  ['/guides/redwoodjs', '/guides/sites_frameworks/getting_started/redwoodjs'],
  ['/guides/remix', '/guides/sites_frameworks/getting_started/remix'],
  ['/guides/saber', '/guides/sites_frameworks/getting_started/saber'],
  ['/guides/sanity', '/guides/sites_frameworks/getting_started/sanity'],
  ['/guides/sapper', '/guides/sites_frameworks/getting_started/sapper'],
  ['/guides/scully', '/guides/sites_frameworks/getting_started/scully'],
  ['/guides/solid', '/guides/sites_frameworks/getting_started/solid'],
  ['/guides/spartacus', '/guides/sites_frameworks/getting_started/spartacus'],
  [
    '/guides/static_sites',
    '/guides/sites_frameworks/getting_started/static_sites',
  ],
  ['/guides/stencil', '/guides/sites_frameworks/getting_started/stencil'],
  ['/guides/svelte', '/guides/sites_frameworks/getting_started/svelte'],
  ['/guides/umijs', '/guides/sites_frameworks/getting_started/umijs'],
  ['/guides/vitepress', '/guides/sites_frameworks/getting_started/vitepress'],
  ['/guides/vsf', '/guides/sites_frameworks/getting_started/vsf'],
  ['/guides/vsf1', '/guides/sites_frameworks/getting_started/vsf1'],
  ['/guides/vue', '/guides/sites_frameworks/getting_started/vue'],
  ['/guides/vuepress', '/guides/sites_frameworks/getting_started/vuepress'],
  ['/guides/zola', '/guides/sites_frameworks/getting_started/zola'],
  ['/guides/security/introduction', '/guides/security'],
  ['/guides/basics/teams', '/guides/basics/collaboration'],
  ['/guides/reference/saml', '/guides/basics/collaboration/sso'],
  ['/guides/basics/deploy_apps', '/guides/basics/deployments'],
  ['/guides/basics/production', '/guides/basics/domains'],
  ['/guides/performance/routing', '/guides/performance/cdn_as_code'],
  [
    '/guides/cookbook',
    '/guides/performance/cdn_as_code/common_routing_patterns',
  ],
  [
    '/guides/performance/getting_started_performance',
    '/guides/performance/getting_started',
  ],
  ['/guides/performance/request_headers', '/guides/performance/request'],
  [
    '/guides/performance/serverless_functions',
    '/guides/performance/serverless_compute',
  ],
  ['/guides/static_prerendering', '/guides/performance/static_prerendering'],
  ['/guides/traditional_sites', '/guides/performance/traditional_sites'],
  [
    '/guides/performance/traffic_splitting/split_testing',
    '/guides/performance/traffic_splitting/a_b_testing',
  ],
  [
    '/guides/performance/edgejs_testing',
    '/guides/performance/unit_testing_edgejs',
  ],
  [
    '/guides/sites_frameworks/getting_started',
    '/guides/sites_frameworks/getting_started',
  ],
  ['/guides/troubleshooting', '/guides/performance/troubleshooting'],
];
