required:
  - '@id'
  - '@type'
  - id
type: object
properties:
  '@type':
    type: string
    description: Resource type.
  '@id':
    type: string
    description: >-
      Used to specify the URI for the resource. Can be used by clients to
      navigate back to that specific resource.
  '@links':
    type: object
    properties: {}
    description: Links to related resources.
  id:
    type: string
    description: Resource unique identifier.
  status:
    type: string
    description: |
      Indicates the status for the deployment.
      Valid values are:
        - `created`: Initial state.
        - `uploading`: Waiting for CLI to upload the build. Only applicable for EdgeJS deployments.
        - `provisioning`: Waiting for the CDN to provision the environment.
        - `deploying`: Deploying the build to cloud & edge.
        - `waiting`: Waiting for the edge propagation to complete.
        - `completed`: Indicates that the deployment has been completed.
        - `canceled`: Indicates that the deployment has been canceled.
        - `failed`: Indicates that the deployment has failed.
  created_at:
    type: string
    description: Indicates the date and time (UTC) at which the deployment was submitted.
    format: date-time
  completed_at:
    type: string
    description: Indicates the date and time (UTC) at which the deployment was completed.
    format: date-time
description: Config_V1_Entities_Deployment model
