type: object
properties:
  '@type':
    type: string
    description: The resource's type.
  '@id':
    type: string
    description: The resource's relative path.
  '@links':
    $ref: ./BaseApi_Entities_HyperionNavigationLinks.yaml
  total_items:
    type: integer
    format: int32
    description: Total number of items.
  items:
    type: array
    items:
      $ref: ./Config_V1_Entities_TlsCert.yaml
    description: List of TLS certificates associated with the specified environment.
required:
  - '@type'
  - '@id'
description: Config_V1_Entities_TlsCert_Collection model
