type: object
properties:
  message:
    type: string
    description: Log message.
  level:
    type: string
    description: Log level.
  timestamp:
    type: string
    description: The date and time (UTC) at which the message was logged.
    format: date-time
