required:
  - '@id'
  - '@type'
type: object
properties:
  '@type':
    type: string
    description: The resource's type.
  '@id':
    type: string
    description: The resource's relative path.
  '@links':
    $ref: ./BaseApi_Entities_HyperionNavigationLinks.yaml
  total_items:
    type: integer
    description: Total number of items.
    format: int32
  items:
    type: array
    description: List of TLS certificates associated with the specified environment.
    items:
      $ref: ./Config_V1_Entities_TlsCert.yaml
description: Config_V1_Entities_TlsCert_Collection model
