type: object
properties:
  '@type':
    type: string
    description: The resource's type.
  '@id':
    type: string
    description: The resource's relative path.
  '@links':
    type: object
    description: Links to related resources.
  id:
    type: string
    description: The resource's system-defined ID.
  status:
    type: string
    description: |
      Indicates the deployment's status. Valid values are:
        - `created`: The deployment has been created but has not yet been deployed.
        - `uploading`: The CLI is uploading the build. This state is only applicable for EdgeJS deployments.
        - `provisioning`: The CDN is provisioning the environment.
        - `deploying`: The build is being deployed to our network.
        - `waiting`: The build is being propagated throughout our network.
        - `completed`: The build was deployed successfully to our network.
        - `canceled`: The deployment was canceled.
        - `failed`: The deployment has failed.
  created_at:
    type: string
    format: date-time
    description: The date and time (UTC) at which the deployment was submitted.
  completed_at:
    type: string
    format: date-time
    description: The date and time (UTC) at which the deployment was completed.
required:
  - '@type'
  - '@id'
  - id
description: Config_V1_Entities_Deployment model
