required:
  - '@id'
  - '@type'
  - id
type: object
properties:
  '@type':
    type: string
    description: Resource type.
  '@id':
    type: string
    description: >-
      Used to specify the URI for the resource. Can be used by clients to
      navigate back to that specific resource.
  '@links':
    type: object
    properties: {}
    description: Links to related resources.
  id:
    type: string
    description: Resource unique identifier.
  origins:
    type: string
    description: List of origins for the configuration.
    example: ''
  hostnames:
    type: string
    description: List of hostnames for the configuration.
    example: ''
  rules:
    type: string
    description: List of rules for the configuration.
    example: ''
  experiments:
    type: string
    description: List of experiments for the configuration.
    example: ''
description: Config_V1_Entities_Config model
