type: object
properties:
  '@type':
    type: string
    description: The resource's type.
  '@id':
    type: string
    description: The resource's relative path.
  '@links':
    type: object
    description: Links to related resources.
  id:
    type: string
    description: The resource's system-defined ID.
  origins:
    $ref: >-
      https://api.vdms.io/cdn/edge-control/v1/configuration/schema#/definitions/property/properties/origins
  hostnames:
    $ref: >-
      https://api.vdms.io/cdn/edge-control/v1/configuration/schema#/definitions/property/properties/hostnames
  rules:
    $ref: >-
      https://api.vdms.io/cdn/edge-control/v1/configuration/schema#/definitions/property/properties/rules
  experiments:
    type: string
    example:
      - {}
    description: List of experiments.
  edge_functions_sources:
    type: string
    example:
      my-edge-function.js: |
        export async function handleHttpRequest(request, context) {
          return new Response(
            JSON.stringify({ message: "Hello from the edge function!"}),
            {
              headers: {
                "Content-Type": "application/json"
              }
            }
          )
        }
    description: |
      JSON object of Edge Functions sources:

      - The **key** denotes the name of the Edge Function.
      - The **value** holds the source of the Edge Function.
required:
  - '@type'
  - '@id'
  - id
description: Config_V1_Entities_Config model
