required:
  - name
  - property_id
type: object
properties:
  property_id:
    type: string
  name:
    type: string
  can_members_deploy:
    type: boolean
  http_request_logging:
    type: boolean
description: Create a new environment
