type: object
properties:
  property_id:
    type: string
    description: The property's system-defined ID.
  name:
    type: string
    description: >
      The environment's name. This name may only consist of lowercase
      characters, numbers, dashes, and underscores.
  can_members_deploy:
    type: boolean
    description: |
      Deprecated by the `only_maintainers_can_deploy` property."
  only_maintainers_can_deploy:
    type: boolean
    description: >
      Determines whether Editors will be restricted to read-only access.
      Enabling this option restricts configuration and deployments to deploy
      tokens, Maintainers, and Admins.
  http_request_logging:
    type: boolean
    description: >-
      Determines whether deep-request inspection for serverless logs will be
      enabled.
required:
  - property_id
  - name
description: Creates an environment.
