required:
  - environment_id
  - intermediate_cert
  - primary_cert
type: object
properties:
  environment_id:
    type: string
  primary_cert:
    type: string
  intermediate_cert:
    type: string
  private_key:
    type: string
description: Upload and activate a new TLS certificate for an environment
