type: object
properties:
  environment_id:
    type: string
    description: >
      An environment's system-defined ID (e.g.,
      12345678-1234-1234-1234-1234567890ab).


      From the Edgio Console, navigate to the desired environment and then click
      **Settings**. It is listed under **Environment ID**.
required:
  - environment_id
description: >-
  Generates a Let's Encrypt certificate for each eligible hostname associated
  with the specified environment. A hostname is eligible for automatic
  certificate generation when the CA is allowed to issue certificates for that
  hostname and your control over the domain is established through an
  `_acme_challenge` CNAME record. [Learn
  more.](https://docs.edg.io/applications/basics/hostnames#https-traffic)
