type: object
properties:
  environment_id:
    type: string
    description: >
      An environment's system-defined ID (e.g.,
      12345678-1234-1234-1234-1234567890ab).


      From the Edgio Console, navigate to the desired environment and then click
      **Settings**. It is listed under **Environment ID**.
  key:
    type: string
    description: The environment variable's name.
  value:
    type: string
    description: The environment variable's value.
  secret:
    type: boolean
    description: >
      Determines whether the environment variable's value will be partially
      masked using asterisks.
required:
  - environment_id
  - key
  - value
description: Creates or updates an environment variable.
