{
  "info": {
    "title": "Edgio Edgio APIs",
    "description": "API spec for Edgio APIs",
    "termsOfService": "https://edg.io/legal/terms-of-service/",
    "contact": {
      "name": "info@edg.io",
      "email": "info@edg.io",
      "url": "https://edg.io/contact-support/"
    },
    "version": "1.0.0-beta"
  },
  "swagger": "2.0",
  "securityDefinitions": {
    "configScope": {
      "type": "oauth2",
      "authorizationUrl": "http://swagger.io/api/oauth/dialog",
      "flow": "implicit",
      "scopes": {
        "app.config": "app.config"
      }
    },
    "cacheScope": {
      "type": "oauth2",
      "authorizationUrl": "http://swagger.io/api/oauth/dialog",
      "flow": "implicit",
      "scopes": {
        "app.cache.purge": "app.cache.purge"
      }
    },
    "accountsScope": {
      "type": "oauth2",
      "authorizationUrl": "http://swagger.io/api/oauth/dialog",
      "flow": "implicit",
      "scopes": {
        "app.accounts": "app.accounts"
      }
    }
  },
  "host": "edgioapis.com",
  "basePath": "/",
  "tags": [
    {
      "name": "members",
      "description": "Operations about members"
    },
    {
      "name": "environments",
      "description": "Operations about environments"
    },
    {
      "name": "properties",
      "description": "Operations about properties"
    },
    {
      "name": "organizations",
      "description": "Operations about organizations"
    },
    {
      "name": "asm",
      "description": "Operations about asms"
    },
    {
      "name": "bff",
      "description": "Operations about bffs"
    },
    {
      "name": "purge-requests",
      "description": "Operations about purge-requests"
    },
    {
      "name": "environment-redirects",
      "description": "Operations about environment-redirects"
    },
    {
      "name": "environment-variables",
      "description": "Operations about environment-variables"
    },
    {
      "name": "tls-certs",
      "description": "Operations about tls-certs"
    },
    {
      "name": "deployments",
      "description": "Operations about deployments"
    },
    {
      "name": "configs",
      "description": "Operations about configs"
    }
  ],
  "paths": {
    "/accounts/v0.1/members/{member_id}": {
      "delete": {
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "members"
        ],
        "operationId": "deleteAccountsV01MembersMemberId"
      },
      "patch": {
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "members"
        ],
        "operationId": "patchAccountsV01MembersMemberId"
      },
      "get": {
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "members"
        ],
        "operationId": "getAccountsV01MembersMemberId"
      }
    },
    "/accounts/v0.1/members": {
      "post": {
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "members"
        ],
        "operationId": "postAccountsV01Members"
      },
      "get": {
        "summary": " members",
        "description": " members",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "members"
        ],
        "operationId": "getAccountsV01Members"
      }
    },
    "/accounts/v0.1/environments/{environment_id}": {
      "delete": {
        "summary": "Delete Environment",
        "description": "Deletes an environment.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "environments"
        ],
        "operationId": "deleteAccountsV01EnvironmentsEnvironmentId"
      },
      "patch": {
        "summary": "Update Environment",
        "description": "Updates an environment.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "environments"
        ],
        "operationId": "patchAccountsV01EnvironmentsEnvironmentId"
      },
      "get": {
        "summary": "Get Environment",
        "description": "Retrieves an environment's settings and metadata.\n",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "environments"
        ],
        "operationId": "getAccountsV01EnvironmentsEnvironmentId"
      }
    },
    "/accounts/v0.1/environments": {
      "post": {
        "summary": "Add Environment",
        "description": "Creates an environment.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "environments"
        ],
        "operationId": "postAccountsV01Environments"
      },
      "get": {
        "summary": "Get All Environments",
        "description": "Returns all environments that belong to the specified property.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "environments"
        ],
        "operationId": "getAccountsV01Environments"
      }
    },
    "/accounts/v0.1/properties/{property_id}": {
      "delete": {
        "summary": "Delete Property",
        "description": "Delete a property.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "properties"
        ],
        "operationId": "deleteAccountsV01PropertiesPropertyId"
      },
      "patch": {
        "summary": "Update Property",
        "description": "Update a property.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "properties"
        ],
        "operationId": "patchAccountsV01PropertiesPropertyId"
      },
      "get": {
        "summary": "Get Property",
        "description": "Retrieve a property.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "properties"
        ],
        "operationId": "getAccountsV01PropertiesPropertyId"
      }
    },
    "/accounts/v0.1/properties": {
      "post": {
        "summary": "Create Property",
        "description": "Create a property.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "properties"
        ],
        "operationId": "postAccountsV01Properties"
      },
      "get": {
        "summary": "Get All Properties",
        "description": "Returns all properties.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "properties"
        ],
        "operationId": "getAccountsV01Properties"
      }
    },
    "/accounts/v0.1/organizations/{organization_id}": {
      "delete": {
        "summary": "Delete Organization",
        "description": "Deletes an organization.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "organizations"
        ],
        "operationId": "deleteAccountsV01OrganizationsOrganizationId"
      },
      "patch": {
        "summary": "Update Organization",
        "description": "Updates an organization.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "organizations"
        ],
        "operationId": "patchAccountsV01OrganizationsOrganizationId"
      },
      "get": {
        "summary": "Get Organization",
        "description": "Retrieves information about an organization.",
        "security": [
          {
            "accountsScope": [
              "app.accounts"
            ]
          }
        ],
        "tags": [
          "organizations"
        ],
        "operationId": "getAccountsV01OrganizationsOrganizationId"
      }
    },
    "/asm/v0.1/proxies/filters": {
      "get": {
        "description": "Returns a list of filters that can be used to filter proxies.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ProxiesFilters"
      }
    },
    "/asm/v0.1/proxies/stats": {
      "get": {
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ProxiesStats"
      }
    },
    "/asm/v0.1/proxies": {
      "get": {
        "description": "Returns a list of Proxies",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Proxies"
      }
    },
    "/asm/v0.1/criterion-types": {
      "get": {
        "description": "Gets all criterion types with their associated operators.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CriterionTypes"
      }
    },
    "/asm/v0.1/context": {
      "get": {
        "description": "Gets all available ASM permissions for the current user.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Context"
      }
    },
    "/asm/v0.1/cwes/{id}": {
      "get": {
        "description": "Gets a CWE",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CwesId"
      }
    },
    "/asm/v0.1/cwes": {
      "get": {
        "description": "Gets all CWEs in our database",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Cwes"
      }
    },
    "/asm/v0.1/cves/{id}": {
      "get": {
        "description": "Gets a CVE",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CvesId"
      }
    },
    "/asm/v0.1/cves/filters": {
      "get": {
        "description": "Returns a list of filters that can be used to filter assets.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CvesFilters"
      }
    },
    "/asm/v0.1/cves": {
      "get": {
        "description": "Gets all CVEs in our database",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Cves"
      }
    },
    "/asm/v0.1/cpe-matches/{id}": {
      "get": {
        "description": "Gets a CPE Match by ID",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CpeMatchesId"
      }
    },
    "/asm/v0.1/cpe-matches": {
      "get": {
        "description": "Gets all CPE Matches in our database",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CpeMatches"
      }
    },
    "/asm/v0.1/cpes/{id}": {
      "get": {
        "description": "Gets a CPE",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CpesId"
      }
    },
    "/asm/v0.1/cpes": {
      "get": {
        "description": "Gets all CPEs in our database",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Cpes"
      }
    },
    "/asm/v0.1/rules/{id}": {
      "patch": {
        "description": "Updates a rule.",
        "tags": [
          "asm"
        ],
        "operationId": "patchAsmV01RulesId"
      },
      "delete": {
        "description": "Deletes a rule.",
        "tags": [
          "asm"
        ],
        "operationId": "deleteAsmV01RulesId"
      }
    },
    "/asm/v0.1/rules/reorder": {
      "patch": {
        "description": "Reorders rules",
        "tags": [
          "asm"
        ],
        "operationId": "patchAsmV01RulesReorder"
      }
    },
    "/asm/v0.1/rules/reset": {
      "delete": {
        "description": "Reset all rules in an organization.",
        "tags": [
          "asm"
        ],
        "operationId": "deleteAsmV01RulesReset"
      }
    },
    "/asm/v0.1/rules": {
      "post": {
        "description": "Create a rule.",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01Rules"
      },
      "get": {
        "description": "Lists all rules in an organization.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Rules"
      }
    },
    "/asm/v0.1/comments/{id}": {
      "delete": {
        "description": "Deletes a comment",
        "tags": [
          "asm"
        ],
        "operationId": "deleteAsmV01CommentsId"
      },
      "patch": {
        "description": "Updates a comment",
        "tags": [
          "asm"
        ],
        "operationId": "patchAsmV01CommentsId"
      },
      "get": {
        "description": "Gets a comment",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CommentsId"
      }
    },
    "/asm/v0.1/comments": {
      "post": {
        "description": "Creates a comment for an exposure.",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01Comments"
      },
      "get": {
        "description": "Lists all comments for an exposure.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Comments"
      }
    },
    "/asm/v0.1/dashboard/world-map": {
      "get": {
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01DashboardWorldMap"
      }
    },
    "/asm/v0.1/dashboard/stats": {
      "get": {
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01DashboardStats"
      }
    },
    "/asm/v0.1/technologies/categories": {
      "get": {
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TechnologiesCategories"
      }
    },
    "/asm/v0.1/technologies/{id}": {
      "get": {
        "description": "Gets a technology",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TechnologiesId"
      }
    },
    "/asm/v0.1/technologies/filters": {
      "get": {
        "description": "Returns a list of filters that can be used to filter technology versions.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TechnologiesFilters"
      }
    },
    "/asm/v0.1/technologies": {
      "get": {
        "description": "Get all matching technologies",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Technologies"
      }
    },
    "/asm/v0.1/technology-versions/{id}": {
      "delete": {
        "description": "Deletes a technology version",
        "tags": [
          "asm"
        ],
        "operationId": "deleteAsmV01TechnologyVersionsId"
      },
      "get": {
        "description": "Gets a technology version",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TechnologyVersionsId"
      }
    },
    "/asm/v0.1/technology-versions/filters": {
      "get": {
        "description": "Returns a list of filters that can be used to filter technology versions.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TechnologyVersionsFilters"
      }
    },
    "/asm/v0.1/technology-versions": {
      "get": {
        "description": "Gets all matching technology versions",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TechnologyVersions"
      }
    },
    "/asm/v0.1/exposures/{id}/scan-results": {
      "get": {
        "description": "Returns the scan results for an exposure.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ExposuresIdScanResults"
      }
    },
    "/asm/v0.1/exposures/{id}/watch": {
      "patch": {
        "description": "Watches/unwatches an exposure.",
        "tags": [
          "asm"
        ],
        "operationId": "patchAsmV01ExposuresIdWatch"
      }
    },
    "/asm/v0.1/exposures/{id}": {
      "patch": {
        "description": "Updates an exposure.",
        "tags": [
          "asm"
        ],
        "operationId": "patchAsmV01ExposuresId"
      },
      "get": {
        "description": "Gets an exposure.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ExposuresId"
      }
    },
    "/asm/v0.1/exposures/bulk-edit": {
      "post": {
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01ExposuresBulkEdit"
      }
    },
    "/asm/v0.1/exposures/timeline": {
      "get": {
        "description": "Returns exposure counts for the last 7 days.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ExposuresTimeline"
      }
    },
    "/asm/v0.1/exposures/count": {
      "get": {
        "description": "Returns a count of exposures by the specified field.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ExposuresCount"
      }
    },
    "/asm/v0.1/exposures/filters": {
      "get": {
        "description": "Returns a list of filters that can be used to filter assets.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ExposuresFilters"
      }
    },
    "/asm/v0.1/exposures": {
      "get": {
        "description": "Lists all exposures matching the specified criteria.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Exposures"
      }
    },
    "/asm/v0.1/scans/{id}/cancel": {
      "post": {
        "description": "cancels a scan",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01ScansIdCancel"
      }
    },
    "/asm/v0.1/scans/{id}": {
      "get": {
        "description": "Gets a scan",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ScansId"
      }
    },
    "/asm/v0.1/scans/filters": {
      "get": {
        "description": "Returns a list of filters that can be used when searching for scans.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01ScansFilters"
      }
    },
    "/asm/v0.1/scans": {
      "get": {
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Scans"
      }
    },
    "/asm/v0.1/tasks/{id}/cancel": {
      "post": {
        "description": "Cancels a task",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01TasksIdCancel"
      }
    },
    "/asm/v0.1/tasks/{id}/retry": {
      "post": {
        "description": "Tries to re-run a failed task",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01TasksIdRetry"
      }
    },
    "/asm/v0.1/tasks/{id}/raw-results": {
      "get": {
        "description": "Gets the results log for a task",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TasksIdRawResults"
      }
    },
    "/asm/v0.1/tasks/{id}": {
      "get": {
        "description": "Gets a task",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TasksId"
      }
    },
    "/asm/v0.1/tasks/filters": {
      "get": {
        "description": "Returns a list of filters that can be used to filter tasks",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01TasksFilters"
      }
    },
    "/asm/v0.1/tasks": {
      "get": {
        "description": "Searches for tasks",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Tasks"
      }
    },
    "/asm/v0.1/assets/{id}/whois": {
      "get": {
        "description": "Gets Whois scan results for the specified asset (as a raw test).",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01AssetsIdWhois"
      }
    },
    "/asm/v0.1/assets/{id}/scan": {
      "post": {
        "description": "Scans the specified asset for issues.",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01AssetsIdScan"
      }
    },
    "/asm/v0.1/assets/{id}": {
      "delete": {
        "description": "Deletes an asset",
        "tags": [
          "asm"
        ],
        "operationId": "deleteAsmV01AssetsId"
      },
      "patch": {
        "description": "Updates an asset",
        "tags": [
          "asm"
        ],
        "operationId": "patchAsmV01AssetsId"
      },
      "get": {
        "description": "Gets an asset",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01AssetsId"
      }
    },
    "/asm/v0.1/assets/bulk-edit": {
      "post": {
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01AssetsBulkEdit"
      }
    },
    "/asm/v0.1/assets/graph": {
      "get": {
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01AssetsGraph"
      }
    },
    "/asm/v0.1/assets/filters": {
      "get": {
        "description": "Returns a list of filters that can be used to filter assets.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01AssetsFilters"
      }
    },
    "/asm/v0.1/assets": {
      "get": {
        "description": "Lists all assets matching the specified criteria.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Assets"
      }
    },
    "/asm/v0.1/seed-types": {
      "get": {
        "description": "Gets all seed types",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01SeedTypes"
      }
    },
    "/asm/v0.1/seeds/{id}": {
      "delete": {
        "description": "Deletes an seed.",
        "tags": [
          "asm"
        ],
        "operationId": "deleteAsmV01SeedsId"
      },
      "patch": {
        "description": "Updates an seed.",
        "tags": [
          "asm"
        ],
        "operationId": "patchAsmV01SeedsId"
      }
    },
    "/asm/v0.1/seeds": {
      "post": {
        "description": "Add a seed to a collection.",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01Seeds"
      }
    },
    "/asm/v0.1/collections/{id}/reset": {
      "post": {
        "description": "Deletes all exposures, assets, and technology versions in a collection.",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01CollectionsIdReset"
      }
    },
    "/asm/v0.1/collections/{id}/scan": {
      "post": {
        "description": "Scans a collection for issues.",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01CollectionsIdScan"
      }
    },
    "/asm/v0.1/collections/{id}": {
      "patch": {
        "description": "Updates a collection.",
        "tags": [
          "asm"
        ],
        "operationId": "patchAsmV01CollectionsId"
      },
      "delete": {
        "description": "Deletes a collection.",
        "tags": [
          "asm"
        ],
        "operationId": "deleteAsmV01CollectionsId"
      },
      "get": {
        "description": "Gets a collection.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01CollectionsId"
      }
    },
    "/asm/v0.1/collections": {
      "post": {
        "description": "Create a collection.",
        "tags": [
          "asm"
        ],
        "operationId": "postAsmV01Collections"
      },
      "get": {
        "description": "Lists all collections in an organization.",
        "tags": [
          "asm"
        ],
        "operationId": "getAsmV01Collections"
      }
    },
    "/bff/rta/alerts/{alert_id}": {
      "put": {
        "tags": [
          "bff"
        ],
        "operationId": "putBffRtaAlertsAlertId"
      },
      "delete": {
        "tags": [
          "bff"
        ],
        "operationId": "deleteBffRtaAlertsAlertId"
      }
    },
    "/bff/rta/alerts": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffRtaAlerts"
      },
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffRtaAlerts"
      }
    },
    "/bff/mtls/chains/{sunfish_chain_id}": {
      "delete": {
        "tags": [
          "bff"
        ],
        "operationId": "deleteBffMtlsChainsSunfishChainId"
      },
      "put": {
        "tags": [
          "bff"
        ],
        "operationId": "putBffMtlsChainsSunfishChainId"
      }
    },
    "/bff/mtls/chains": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffMtlsChains"
      },
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffMtlsChains"
      }
    },
    "/bff/mtls/config": {
      "delete": {
        "tags": [
          "bff"
        ],
        "operationId": "deleteBffMtlsConfig"
      },
      "put": {
        "tags": [
          "bff"
        ],
        "operationId": "putBffMtlsConfig"
      },
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffMtlsConfig"
      }
    },
    "/bff/rtld/fields": {
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffRtldFields"
      }
    },
    "/bff/rtld/countries": {
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffRtldCountries"
      }
    },
    "/bff/rtld/metadata/{metadata_type}": {
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffRtldMetadataMetadataType"
      }
    },
    "/bff/rtld/{profile_type}/profiles/{profile_id}": {
      "delete": {
        "tags": [
          "bff"
        ],
        "operationId": "deleteBffRtldProfileTypeProfilesProfileId"
      },
      "put": {
        "tags": [
          "bff"
        ],
        "operationId": "putBffRtldProfileTypeProfilesProfileId"
      }
    },
    "/bff/rtld/{profile_type}/profiles": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffRtldProfileTypeProfiles"
      },
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffRtldProfileTypeProfiles"
      }
    },
    "/bff/rtld/stats": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffRtldStats"
      }
    },
    "/bff/ids/teams/{team_id}/feature-scopes": {
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffIdsTeamsTeamIdFeatureScopes"
      }
    },
    "/bff/ids/teams/{team_id}/clients/{client_id}/secrets/{secret_id}": {
      "delete": {
        "tags": [
          "bff"
        ],
        "operationId": "deleteBffIdsTeamsTeamIdClientsClientIdSecretsSecretId"
      }
    },
    "/bff/ids/teams/{team_id}/clients/{client_id}/secrets": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffIdsTeamsTeamIdClientsClientIdSecrets"
      },
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffIdsTeamsTeamIdClientsClientIdSecrets"
      }
    },
    "/bff/ids/teams/{team_id}/clients/{client_id}": {
      "delete": {
        "tags": [
          "bff"
        ],
        "operationId": "deleteBffIdsTeamsTeamIdClientsClientId"
      },
      "patch": {
        "tags": [
          "bff"
        ],
        "operationId": "patchBffIdsTeamsTeamIdClientsClientId"
      }
    },
    "/bff/ids/teams/{team_id}/clients": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffIdsTeamsTeamIdClients"
      },
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffIdsTeamsTeamIdClients"
      }
    },
    "/bff/ids/teams/{team_id}/integration": {
      "delete": {
        "tags": [
          "bff"
        ],
        "operationId": "deleteBffIdsTeamsTeamIdIntegration"
      },
      "patch": {
        "tags": [
          "bff"
        ],
        "operationId": "patchBffIdsTeamsTeamIdIntegration"
      },
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffIdsTeamsTeamIdIntegration"
      },
      "get": {
        "tags": [
          "bff"
        ],
        "operationId": "getBffIdsTeamsTeamIdIntegration"
      }
    },
    "/bff/serverless/{query_name}": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffServerlessQueryName"
      }
    },
    "/bff/cwv/{query_name}": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffCwvQueryName"
      }
    },
    "/bff/cwv/staff-top-hosts": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffCwvStaffTopHosts"
      }
    },
    "/bff/traffic/{query_name}": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffTrafficQueryName"
      }
    },
    "/bff/traffic/staff-top-hosts": {
      "post": {
        "tags": [
          "bff"
        ],
        "operationId": "postBffTrafficStaffTopHosts"
      }
    },
    "/cache/v0.1/purge-requests/{request_id}": {
      "get": {
        "summary": "Get Purge Request",
        "description": "Retrieves information, including status, about a purge request.",
        "security": [
          {
            "cacheScope": [
              "app.cache.purge"
            ]
          }
        ],
        "tags": [
          "purge-requests"
        ],
        "operationId": "getCacheV01PurgeRequestsRequestId"
      }
    },
    "/cache/v0.1/purge-requests": {
      "post": {
        "summary": "Purge Cache",
        "description": "Submits a request to purge cached content from a specific environment. Purging content invalidates the cached version of an asset from our edge servers. You may submit up to 50 concurrent purge requests. For the purpose of concurrency, each value defined within the `values` property is considered a separate purge request. Find out the current status of your purge request by passing the purge request ID, which is returned by the `id` property, to the [Get Purge Request ope[...]",
        "security": [
          {
            "cacheScope": [
              "app.cache.purge"
            ]
          }
        ],
        "tags": [
          "purge-requests"
        ],
        "operationId": "postCacheV01PurgeRequests"
      }
    },
    "/config/v0.1/environment-redirects/{environment_redirect_id}": {
      "delete": {
        "summary": "Delete Bulk Redirect",
        "description": "Deletes a bulk redirect.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "environment-redirects"
        ],
        "operationId": "deleteConfigV01EnvironmentRedirectsEnvironmentRedirectId"
      },
      "get": {
        "summary": "Get Bulk Redirect",
        "description": "Returns a bulk redirect.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "environment-redirects"
        ],
        "operationId": "getConfigV01EnvironmentRedirectsEnvironmentRedirectId"
      }
    },
    "/config/v0.1/environment-redirects": {
      "put": {
        "summary": "Set Bulk Redirect",
        "description": "Creates or updates a bulk redirect.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "environment-redirects"
        ],
        "operationId": "putConfigV01EnvironmentRedirects"
      },
      "get": {
        "summary": "Get All Bulk Redirects",
        "description": "Returns all bulk redirects associated with an environment.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "environment-redirects"
        ],
        "operationId": "getConfigV01EnvironmentRedirects"
      }
    },
    "/config/v0.1/environment-variables/{environment_variable_id}": {
      "delete": {
        "summary": "Delete Environment Variable",
        "description": "Deletes an environment variable.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "environment-variables"
        ],
        "operationId": "deleteConfigV01EnvironmentVariablesEnvironmentVariableId"
      },
      "get": {
        "summary": "Get Environment Variable",
        "description": "Returns an environment variable.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "environment-variables"
        ],
        "operationId": "getConfigV01EnvironmentVariablesEnvironmentVariableId"
      }
    },
    "/config/v0.1/environment-variables": {
      "put": {
        "summary": "Set Environment Variable",
        "description": "Creates or updates an environment variable.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "environment-variables"
        ],
        "operationId": "putConfigV01EnvironmentVariables"
      },
      "get": {
        "summary": "Get All Environment Variables",
        "description": "Returns all environment variables associated with an environment.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "environment-variables"
        ],
        "operationId": "getConfigV01EnvironmentVariables"
      }
    },
    "/config/v0.1/tls-certs/{cert_id}": {
      "get": {
        "summary": "Get TLS Certificate",
        "description": "Returns a TLS certificate.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "tls-certs"
        ],
        "operationId": "getConfigV01TlsCertsCertId"
      }
    },
    "/config/v0.1/tls-certs/generate": {
      "post": {
        "summary": "Generate TLS Certificates",
        "description": "Generates a Let's Encrypt certificate for each eligible hostname associated with the specified environment. A hostname is eligible for automatic certificate generation when the CA is allowed to issue certificates for that hostname and your control over the domain is established through an `_acme_challenge` CNAME record. [Learn more.](https://docs.edg.io/applications/basics/hostnames#https-traffic)",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "tls-certs"
        ],
        "operationId": "postConfigV01TlsCertsGenerate"
      }
    },
    "/config/v0.1/tls-certs": {
      "post": {
        "summary": "Upload TLS Certificate",
        "description": "Upload your TLS certificate to activate it within a specific environment.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "tls-certs"
        ],
        "operationId": "postConfigV01TlsCerts"
      },
      "get": {
        "summary": "Get All TLS Certificates",
        "description": "Returns all TLS certificates associated with an environment.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "tls-certs"
        ],
        "operationId": "getConfigV01TlsCerts"
      }
    },
    "/config/v0.1/deployments/{deployment_id}/logs": {
      "get": {
        "summary": "Get Deployment Logs",
        "description": "Retrieve log data for a specific deployment.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "deployments"
        ],
        "operationId": "getConfigV01DeploymentsDeploymentIdLogs"
      }
    },
    "/config/v0.1/deployments/{deployment_id}": {
      "get": {
        "summary": "Get Deployment",
        "description": "Retrieve information about a specific deployment.",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "deployments"
        ],
        "operationId": "getConfigV01DeploymentsDeploymentId"
      }
    },
    "/config/v0.1/configs/{config_id}": {
      "get": {
        "summary": "Get CDN Configuration",
        "description": "Retrieve an environment's origin configurations, hostnames, rules, and experiments.\n",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "configs"
        ],
        "operationId": "getConfigV01ConfigsConfigId"
      }
    },
    "/config/v0.1/configs": {
      "post": {
        "summary": "Deploy CDN Configuration",
        "description": "Deploys your configuration to a specific environment. This deployment overwrites any existing origin configurations, hostnames, rules, and experiments.\n",
        "security": [
          {
            "configScope": [
              "app.config"
            ]
          }
        ],
        "tags": [
          "configs"
        ],
        "operationId": "postConfigV01Configs"
      }
    }
  }
}
